### ISSUE TITLE
[Suggestion] Option to not modify console

### ISSUE THREAD

**Issue by he3als** [couleur-tweak-tips/smoothie-rs#10]
It would be good if there was an option to not modify the console by default, as in, not repositioning it, making it top-most, etc...

**Comment by couleurm** [comment]
I'm thinking about designing it this way:

- User clicks the shortcuts in send to / start menu which contain `--tui` argument, window is resized
- User runs from `sm` on the command line with `--tui`, window is resized


- User runs from `sm` on the command line with `--verbose`, which do not display a progress bar (just FFmpeg stats), window is never resized
- User runs from `sm` on the command line  with neither `--verbose` or `--tui` window is not resized

recipe's `[console]` could also be configured like so (not sure if that will work on your release, try it 🤷‍♂️)
```ini
[console]
stay on top: no
borderless: no
position: 
```

**Comment by he3als** [comment]
That snippet does work, thank you. Maybe it could be documented (when there is proper documentation) in the future (about the `position`)?

Changing the window back to its original state on any error also might be a good option.
