### ISSUE TITLE
Descending and ascending are the opposite

### ISSUE THREAD

**Issue by spenduo** [couleur-tweak-tips/smoothie-rs#26]
Here is descending being used: [Descending](https://user-images.githubusercontent.com/80223997/233274302-3ce5f7fb-c36e-48ba-91c4-63e09a84ba5f.MP4)
Here is ascending being used: [Ascending](https://user-images.githubusercontent.com/80223997/233274568-78bf245d-66bc-4329-bfc7-cae89d1d92db.MP4)

**Comment by couleurm** [comment]
yes.. I'm confused why you opened an issue about this?

**Comment by spenduo** [comment]
oh what should i do (or not) instead?

**Comment by couleurm** [comment]
weighting are just details, do whatever you like 👍, i like ascending @ 60fps with 1.2 intensity

**Comment by couleurm** [comment]
fixed in #46
