### ISSUE TITLE
[Suggestion] Allow the usage of variables in the file format

### ISSUE THREAD

**Issue by Thqrn** [couleur-tweak-tips/smoothie-rs#31]
Instead of just having `file format: %FILENAME% ~ %FRUIT%`, we could have `file format: %FILENAME% ~ %WEIGHTING% %BLURAMOUNT% %INTERPFPS%` or something like that. Would be very useful for render tests.

**Comment by couleurm** [comment]
yup very cool QoL niche thing 0.01% of users would use, not a priority but if someone makes a good PR i'll consider it

i've already implemented %FILENAME% and another var somewhere in the code, shouldn't be too hard

**Comment by couleurm** [comment]
#32
