### ISSUE TITLE
on nightly it won work 

### ISSUE THREAD

**Issue by goofygoober12345** [couleur-tweak-tips/smoothie-rs#34]
![image](https://github.com/couleur-tweak-tips/smoothie-rs/assets/141187041/ec5c63d4-3f16-4502-8679-49e18cee66b8)

**Comment by goofygoober12345** [comment]
help pls quickly

**Comment by Z1xus** [comment]
You need to have FFmpeg installed in order to use smoothie-rs.
```ps
powershell -noe "iex(irm tl.ctt.cx); Get FFmpeg"
```
This command will install Scoop packet manager and FFmpeg.

**Comment by couleurm** [comment]
@goofygoober12345 hello goofy goober one two three four five, please reopen this if you stil have pro blem
