### ISSUE TITLE
Resize error 3074: colorspace bug causes Smoothie to crash

### ISSUE THREAD

**Issue by couleurm** [couleur-tweak-tips/smoothie-rs#36]
![image](https://github.com/couleur-tweak-tips/smoothie-rs/assets/82747632/b142d212-a288-41bd-8867-8664760281cf)
color sometime hecks up with pre-interp

**Comment by couleurm** [comment]
In OBS' advanced settings, setting the color space as sRGB fixes it (quote of leiko)

**Comment by couleurm** [comment]
i could also convert every video which goes through to sRGB to fix that but that could hurt color accuracy

**Comment by couleurm** [comment]
z1xus left some interesting ffmpeg arguments regarding color accuracy in a duplicate issues: https://github.com/couleur-tweak-tips/smoothie-rs/issues/37#issuecomment-1813466575

**Comment by aimslut** [comment]
Friend getting the same error
Initially thought it was colorspace related due to the error description, however it only happens on a clip that's been merged in Lossless-Cut
Blurring the clips without merging them works completely fine 🤔

**Comment by couleurm** [comment]
I gotta fix the matrix guesswork, here's a temporary manual fix:

![image](https://github.com/couleur-tweak-tips/smoothie-rs/assets/82747632/ffe8d890-ee85-487b-bb00-0876df4a0805)
```Python
og_matrix = 1 #clip.get_frame(0).props._Matrix
clip = clip.std.SetFrameProps(_Matrix=vs.MATRIX_BT709)
```

**Comment by couleurm** [comment]
fixed https://github.com/couleur-tweak-tips/smoothie-rs/commit/a2be0192349f3dbc512e38a5930d8814b942abe0
