### ISSUE TITLE
ffmpeg issue

### ISSUE THREAD

**Issue by githubpub900** [couleur-tweak-tips/smoothie-rs#37]
cant find ffmpeg, even tho i put it in the bin folder of smoothie, and in the folder of the video

**Comment by githubpub900** [comment]
Ok i fixed that, but now im stuck at a point where it doesnt let me add motionblur, it opens but it doesnt add motionblur, it just exports it regulary

**Comment by couleurm** [comment]
enable stuff in the recipe, or did you not touch it

**Comment by githubpub900** [comment]
ok well now its just stuck on this after modification
sRGB video, no preinterp or anything like that, only happens with fram
![aasssssssssssddddddddddddd](https://github.com/couleur-tweak-tips/smoothie-rs/assets/73917771/933c2329-071f-4dc1-b763-328edeba761e)
e blendong,

**Comment by Z1xus** [comment]
user provided [input video file](https://drive.google.com/file/d/1-K79CDdwDAOO3NUNizspGCj8AGif7TFn/view?usp=sharing) in discord
they used amd cpu encoder, colorspace of the video stream:
```
color_space=bt709
color_primaries=reserved
color_transfer=iec61966-2-1
```
manually setting these to bt709 with bitstream filter fixed the issue:
```bash
ffmpeg -y -i "2023-11-12 12-32-30.mkv" -map 0 -c copy -map_metadata 0 -bsf:v h264_metadata=colour_primaries=1:transfer_characteristics=1:matrix_coefficients=1 "2023-11-12 12-32-30_out.mkv"
```

colors havent changed:
<details><summary>comparison</summary>
<p>

![image](https://github.com/couleur-tweak-tips/smoothie-rs/assets/40185941/6179306f-4c38-4e01-b55f-3a1e44c6c523)

</p>
</details>

**Comment by couleurm** [comment]
duplicate of #36
