### ISSUE TITLE
Resize error 3070: incompatible color space parameters

### ISSUE THREAD

**Issue by githubpub900** [couleur-tweak-tips/smoothie-rs#38]
![aasssssssssssddddddddddddd](https://github.com/couleur-tweak-tips/smoothie-rs/assets/73917771/160d2019-b8ea-49ed-b4a3-91cdc40bc759)
I RECORDED IN sRGB AND I GOT THIS WHEN FRAME BLENDING,

**Comment by couleurm** [comment]
yes, known issue, try other advanced color format settings in OBS

**Comment by couleurm** [comment]
duplicate of #36

**Comment by githubpub900** [comment]
Tell me some working colorspace paramters, of what YOU use.
