### ISSUE TITLE
what colorspace does smoothie use

### ISSUE THREAD

**Issue by githubpub900** [couleur-tweak-tips/smoothie-rs#39]

**Comment by githubpub900** [comment]
i tried sRGB, and made a post about this earlier, and i was told to try advanced colorspaces, how do i do that, and what colorspace do i use

**Comment by couleurm** [comment]
honestly i dont even know what cursed pact i made with color demons to make this work just try out 1 second long recording yourself and see what crashes and not crashes

also refer to this https://github.com/couleur-tweak-tips/smoothie-rs/blob/main/target/jamba.vpy

for my usecase sRGB Limited works fine..?

**Comment by couleurm** [comment]
duplicate of #36
