### ISSUE TITLE
Error opening input: Invalid data found when processing input

### ISSUE THREAD

**Issue by eqkvak** [couleur-tweak-tips/smoothie-rs#41]
![image](https://github.com/couleur-tweak-tips/smoothie-rs/assets/121827640/2b38a877-56e4-4909-9806-940be5d5b2ea)

Followed a tutorial on installing Smoothie-RS but I am getting errored out, same thing with using the old / new blur (ffmpeg and python are correctly installed and recognizable by path). 

i7 13700h
RTX 4050 45w (Game Ready Driver 546.33)

**Comment by gem-storm** [comment]
The error says `No video track found`; are you sure that you are properly sending a video? And If so, run this command in cmd and send the output:
```
ffprobe <insert path to clip here>
```

**Comment by eqkvak** [comment]
You're right, there indeed was something wrong with that video. Sorry for wasting your time.

**Comment by couleurm** [comment]
np
