### ISSUE TITLE
COPY/OPUS should be default

### ISSUE THREAD

**Issue by vladaad** [couleur-tweak-tips/smoothie-rs#42]
Without these args, the audio is re-encoded to very low quality using FFmpeg's default codec for the container. Possibly add a preset by default that just adds `-b:a 320k` to preserve compatibility and audio quality.

**Comment by couleurm** [comment]
How can I tell if the user did not use their own audio enc args? It'd need to parse -c:a and its aliases, check for audio filters in filter complex..

**Comment by couleurm** [comment]
> How can I tell if the user did not use their own audio enc args? It'd need to parse -c:a and its aliases, check for audio filters in filter complex..

I'd love to consider this but this reason holds me back, if you find a clever trick to circumvent having to parse for ffmpeg cli args please reopen this
