### ISSUE TITLE
Not being able to set the exact fps number in the interpolation

### ISSUE THREAD

**Issue by Latokes** [couleur-tweak-tips/smoothie-rs#52]
`Just copied my message from ctt dis.`
There is one thing i didn't really like. For example: if i want to interpolate my video like this 360 (original) -> 360*2, i absolutely cannot do it from gui, even just typing 720, since it basically becomes 780. So i have to go to recipe.ini in change it manually. 
Is it a bug or a feature? 
Maybe add some type of basic calculator in this specific window?

https://github.com/couleur-tweak-tips/smoothie-rs/assets/145843529/c10deb50-afa9-41c0-a14d-256a76c7afeb

**Comment by june1025** [comment]
@Latokes try and change the interpolation `increment` metadata in the `defaults.ini` file

**Comment by Latokes** [comment]
> @Latokes try and change the interpolation `increment` metadata in the `defaults.ini` file

Thank you. Im closing the ticket then.

**Comment by Latokes** [comment]
@june1025 was there to help
