### ISSUE TITLE
Use GPU doesn't really work?

### ISSUE THREAD

**Issue by Kanibal02** [couleur-tweak-tips/smoothie-rs#55]
So
```
[interpolation]
enabled: yes
masking: yes
fps: 480
speed: medium
tuning: film
algorithm: 23
use gpu: yes
```

In the first Lines of the recpie.ini
the `use gpu: yes/no` seems to do mostly nothing, at least for my example, for my GTX 970, is there any other things I can change, to really use my GPU? Or I should just get a better GPU, to see the difference 

(I'm Getting RTX 4070 super, in a few days, if I don't get a response, I'm just going to test it with the RTX, and see if its faster or no)

 And I don't see any other options, where I can use the GPU.

**Comment by couleurm** [comment]
svpflow (the interp plugin) is a bit cryptic, turn it on if you can

also you can use your gpu to encode with nvenc

**Comment by Kanibal02** [comment]
what? where do i find it, and change it?

**Comment by couleurm** [comment]
see enc args in ctt.cx/recipe#output

**Comment by Kanibal02** [comment]
alr i changed it from h265 cpu to h265 NVENC and it helps very much, going from average of 0.2x to 0.4x, on my gtx gpu now, i'll see tomorow the change, it will probably jump by another 0.2x or even up to 1x or more!, thanks for the help

**Comment by Kanibal02** [comment]
now that i have the RTX, i see the speeds being really the same, but still the jump from 0.2x to 0.4x is just double, whatever, thanks for the help
